### ISSUE TITLE
Fields work, but not as intended

### ISSUE THREAD

**Issue by daved** [ioalessio/IoFormBundle#5]
I have installed this bundle and reviewed my work numerous times.  When using the combobox, an entity field type shows up.  When using a tinymce field type, a text area shows up.  When using the datepicker and range field types, a text box shows up.

I am using Symfony 2.0.3, and I have tried numerous versions of the required javascripts.

I am sorry that I can't contribute to a solution, and more so if this is my own fault.  I am still in the beginning stages of building up my abilities.

**Comment by daved** [comment]
I'm glad and embarrassed to say that this did work out to be my own fault.  I took some of the Symfony documentation too strictly and let that override my better judgment regarding JS placement.

Thanks for a great bundle and sorry for the interruption!

**Comment by zhil** [comment]
Well, I have exactly the same issue - how did you solved it? :)

**Comment by zhil** [comment]
I would say, that its a bug, opened new issue here
https://github.com/ioalessio/IoFormBundle/issues/7

**Comment by daved** [comment]
I'm not sure that my issue is the same as yours, but my solution was basic.  In the Symfony 2 book, the "javascripts" twig block (http://symfony.com/doc/2.0/book/page_creation.html - around half way down) is placed in the body of the template.  As I started to need scripts that should be placed in the head, I failed to catch this simple problem.  Once I placed the appropriate scripts in their own "jshead" block, and left the others in the body, everything worked fine.

I've been so wrapped up in getting up to speed on OOP that I neglected one of the basics!

**Comment by zhil** [comment]
Yes, I had the same issue.

And its actually nice solution - to place JS code includes after main body instead of putting them in head section.
That will increase page rendering speed.

We discuss it with bundle creator here
https://github.com/ioalessio/IoFormBundle/issues/7
